-- Japanese romaji engine. All data lives in data.json (generated by
-- scripts/gen_jp_data.py from the Unicode Unihan database); this module
-- only holds logic.

local data = require("flash-cjk.lang").data("ja")

local M = {}

-- Romaji prefix length -> lookup table.
local patterns = { data.p1, data.p2, data.p3 }

---Returns the vim regex fragment for a 1-3 letter romaji prefix,
---or nil when nothing matches it. Fragments may cover two characters
---at once (youon combos: しゃ for "sha").
---@param prefix string
---@return string?
function M.pattern(prefix)
	local table = patterns[#prefix]
	if table then
		return table[prefix]
	end
end

local char_size = require("flash-cjk.util").char_size

-- Small y-kana (youon second half), keyed by the vowel they add.
local SMALL_Y = {
	["ゃ"] = "a",
	["ゅ"] = "u",
	["ょ"] = "o",
	["ャ"] = "a",
	["ュ"] = "u",
	["ョ"] = "o",
}

-- Mirrors merge_youon() in the generator: き+ゃ -> kya, し+ゃ -> sha.
local function youon_merged(base, vowel)
	if base == "shi" or base == "chi" or base == "ji" then
		return string.sub(base, 1, -2) .. vowel
	end
	return string.sub(base, 1, -2) .. "y" .. vowel
end

---All romaji spellings the given text could have been typed as.
---Multi-byte characters without a known reading pass through as-is.
---@param text string
---@param cap integer? max number of returned strings
---@return string[]
function M.strs(text, cap)
	cap = cap or 64
	local strs = { "" }
	local i = 1
	while i <= #text do
		local size = char_size(text, i)
		local ch = string.sub(text, i, i + size - 1)
		local next_size = char_size(text, i + size)
		local next_ch = string.sub(text, i + size, i + size + next_size - 1)
		local romas
		if size == 1 then
			romas = { ch }
		else
			local readings = data.readings[ch]
			if not readings then
				romas = { ch }
			elseif SMALL_Y[next_ch] then
				-- small y-kana: merge into preceding i-ending readings
				romas = {}
				for _, reading in ipairs(readings) do
					if #reading >= 2 and string.sub(reading, -1) == "i" then
						romas[#romas + 1] = youon_merged(reading, SMALL_Y[next_ch])
					else
						romas[#romas + 1] = reading -- direct input (xya, lya, ...)
					end
				end
				size = size + next_size -- consume the small kana too
			else
				romas = readings
			end
		end
		local expanded = {}
		for _, str in ipairs(strs) do
			for _, roma in ipairs(romas) do
				if #expanded < cap then
					expanded[#expanded + 1] = str .. roma
				end
			end
		end
		strs = expanded
		i = i + size
	end
	return strs
end

M.comma = data.comma -- 。 is shared with zhcn

return M
