-- Japanese romaji support for flash-cjk.
-- All data tables live in jp_data.lua (generated by scripts/gen_jp_data.py
-- from the Unicode Unihan database); this module only holds logic.
local data = require("flash-cjk.jp_data")

local M = {}

-- Maps a romaji prefix length to its lookup table.
local patterns = { data.p1, data.p2, data.p3 }

---Returns the vim regex fragment for a 1-3 letter romaji prefix,
---or nil when nothing matches it. Fragments may cover two characters
---at once (youon combos: しゃ for "sha").
---@param prefix string
---@return string?
function M.pattern(prefix)
	local t = patterns[#prefix]
	if t then
		return t[prefix]
	end
end

-- ---------------------------------------------------------------------
-- reading expansion
-- Used by the labeler to predict which letter the user may type next
-- for a matched text.

local function char_size(str, i)
	local b = string.byte(str, i)
	if not b then
		return 0
	elseif b > 240 then
		return 4
	elseif b > 225 then
		return 3
	elseif b > 192 then
		return 2
	end
	return 1
end

local SMALL_Y = {
	["ゃ"] = "a", ["ゅ"] = "u", ["ょ"] = "o",
	["ャ"] = "a", ["ュ"] = "u", ["ョ"] = "o",
}

-- Mirrors merge_youon() in the generator: き+ゃ -> kya, し+ゃ -> sha.
local function youon_merged(base, vowel)
	if base == "shi" or base == "chi" or base == "ji" then
		return string.sub(base, 1, -2) .. vowel
	end
	return string.sub(base, 1, -2) .. "y" .. vowel
end

---All romaji spellings the given text could have been typed as.
---Multi-byte characters without a known reading pass through as-is.
---@param text string
---@param cap integer? max number of returned strings
---@return string[]
function M.romaji_strs(text, cap)
	cap = cap or 64
	local strs = { "" }
	local i = 1
	while i <= #text do
		local size = char_size(text, i)
		local ch = string.sub(text, i, i + size - 1)
		local next_size = char_size(text, i + size)
		local next_ch = string.sub(text, i + size, i + size + next_size - 1)
		local romas
		if size == 1 then
			romas = { ch }
		else
			local rs = data.readings[ch]
			if not rs then
				romas = { ch }
			elseif SMALL_Y[next_ch] then
				-- small y-kana: merge into preceding i-ending readings
				romas = {}
				for _, r in ipairs(rs) do
					if #r >= 2 and string.sub(r, -1) == "i" then
						romas[#romas + 1] = youon_merged(r, SMALL_Y[next_ch])
					else
						romas[#romas + 1] = r -- direct input (xya, lya, ...)
					end
				end
				size = size + next_size -- consume the small kana too
			else
				romas = rs
			end
		end
		local next = {}
		for _, s in ipairs(strs) do
			for _, r in ipairs(romas) do
				if #next < cap then
					next[#next + 1] = s .. r
				end
			end
		end
		strs = next
		i = i + size
	end
	return strs
end

-- Japanese punctuation map (self-contained: ASCII + Japanese marks).
-- 。 is shared with Chinese.
M.comma = {
	[","] = "[,、]",
	["."] = "[.。]",
	["["] = "[\\[「『]",
	["]"] = "[\\]」』]",
	["?"] = "[?？]",
	["!"] = "[!！]",
	["-"] = "[ー‐-]",
}

return M
