package.path = "./lua/?.lua;./lua/?/init.lua;" .. package.path
-- Exports the JSON dictionaries to Rust static data: rust/data/*.rs and
-- rust/crates/flash-cjk-core/src/data/*.rs. Run: nvim -l scripts/export_rs.lua
-- Single source of truth: lua/flash-cjk/lang/*/data.json.

local lang = require("flash-cjk.lang")

local function esc(s)
	return (s:gsub('[\\"]', { ["\\"] = "\\\\", ['"'] = '\\"' }))
end

local function write_file(path, lines)
	local f = assert(io.open(path, "w"))
	f:write(table.concat(lines, "\n"))
	f:write("\n")
	f:close()
	print("wrote " .. path)
end

local function sorted_keys(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	return keys
end

-- ---------------------------------------------------------------- zhcn

local zhcn = lang.data("zhcn")

-- "[chars]" values -> ("key", "inner chars") entries, escaped for Rust
local function class_entries(t)
	local out = {}
	for _, k in ipairs(sorted_keys(t)) do
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(t[k]:sub(2, -2)))
	end
	return out
end

write_file("rust/data/zhcn_data.rs", {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/lang/zhcn/data.json -- DO NOT EDIT",
	"// Keys are 1-2 letter xiaohe double-pinyin codes; values are raw character-set strings.",
	"pub static CN_CHAR1: &[(&str, &str)] = &[",
	table.concat(class_entries(zhcn.char1patterns), ",\n"),
	"];",
	"",
	"pub static CN_CHAR2: &[(&str, &str)] = &[",
	table.concat(class_entries(zhcn.char2patterns), ",\n"),
	"];",
})

-- ---------------------------------------------------------------- ja

local ja_data = lang.data("ja")

-- p3 values are "[class]" or "\(class\|literal\|literal\)": split into
-- the class part and the literal two-char alternatives.
local function p3_entries(t)
	local classes, literals = {}, {}
	for _, k in ipairs(sorted_keys(t)) do
		local v = t[k]
		if v:sub(1, 2) == "\\(" then
			for _, part in ipairs(vim.split(v:sub(3, -3), "\\|", { plain = true })) do
				if part:sub(1, 1) == "[" then
					classes[#classes + 1] =
						string.format('("%s", "%s")', esc(k), esc(part:sub(2, -2)))
				else
					literals[#literals + 1] = string.format('("%s", "%s")', esc(k), esc(part))
				end
			end
		else
			classes[#classes + 1] = string.format('("%s", "%s")', esc(k), esc(v:sub(2, -2)))
		end
	end
	return classes, literals
end

local p3_classes, p3_literals = p3_entries(ja_data.p3)

-- char -> comma-separated spellings, for labeler prediction
local function readings_entries(t)
	local out = {}
	for _, k in ipairs(sorted_keys(t)) do
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(table.concat(t[k], ",")))
	end
	return out
end

write_file("rust/data/ja_data.rs", {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/lang/ja/data.json -- DO NOT EDIT",
	"// Romaji prefix -> character set (raw string), split by prefix length.",
	"pub static JP_P1: &[(&str, &str)] = &[",
	table.concat(class_entries(ja_data.p1), ",\n"),
	"];",
	"",
	"pub static JP_P2: &[(&str, &str)] = &[",
	table.concat(class_entries(ja_data.p2), ",\n"),
	"];",
	"",
	"// 3-letter prefixes: single-char classes and youon two-char literals.",
	"pub static JP_P3_CLASS: &[(&str, &str)] = &[",
	table.concat(p3_classes, ",\n"),
	"];",
	"",
	"pub static JP_P3_LIT: &[(&str, &str)] = &[",
	table.concat(p3_literals, ",\n"),
	"];",
	"",
	"// labeler support: char -> spellings (comma separated)",
	"pub static JP_READINGS: &[(&str, &str)] = &[",
	table.concat(readings_entries(ja_data.readings), ",\n"),
	"];",
})

-- ---------------------------------------------------------------- ko

local jamo = lang.data("ko")

local function rust_str(v)
	return '"' .. esc(v) .. '"'
end

local ko_lines = {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/lang/ko/data.json -- DO NOT EDIT",
	"// Korean jamo tables, index-aligned by 0-based L/V/T (None marks the",
	"// tense shift jamo that plain lowercase typing cannot produce).",
	"",
	string.format("pub static KO_L_ROMA: [&[&str]; %d] = [", #jamo.l_roma),
}
for _, romas in ipairs(jamo.l_roma) do
	local parts = {}
	for _, roma in ipairs(romas) do
		parts[#parts + 1] = rust_str(roma)
	end
	ko_lines[#ko_lines + 1] = "    &[" .. table.concat(parts, ", ") .. "],"
end
ko_lines[#ko_lines + 1] = "];"

local function ko_flat(name, arr)
	ko_lines[#ko_lines + 1] = ""
	ko_lines[#ko_lines + 1] = string.format("pub static %s: [&str; %d] = [", name, #arr)
	for _, v in ipairs(arr) do
		ko_lines[#ko_lines + 1] = "    " .. rust_str(v) .. ","
	end
	ko_lines[#ko_lines + 1] = "];"
end
ko_flat("KO_V_ROMA", jamo.v_roma)
ko_flat("KO_T_ROMA", jamo.t_roma)

-- Key tables are index-aligned with the roma arrays; the roma lengths
-- are the authority, since # on holed arrays is a border.
local function ko_opts(name, keys, n)
	ko_lines[#ko_lines + 1] = ""
	ko_lines[#ko_lines + 1] = string.format("pub static %s: [Option<&str>; %d] = [", name, n)
	for i = 0, n - 1 do
		local v = keys[i + 1]
		ko_lines[#ko_lines + 1] = "    " .. (v and ("Some(" .. rust_str(v) .. ")") or "None") .. ","
	end
	ko_lines[#ko_lines + 1] = "];"
end
ko_opts("KO_L_KEYS", jamo.l_keys, #jamo.l_roma)
ko_opts("KO_V_KEYS", jamo.v_keys, #jamo.v_roma)
ko_opts("KO_T_KEYS", jamo.t_keys, #jamo.t_roma)

write_file("rust/crates/flash-cjk-core/src/data/ko.rs", ko_lines)

-- ---------------------------------------------------------------- punct
-- Punctuation per language: vim collection "[chars]" -> inner chars
-- (backslash escapes kept; the Rust side strips them).

write_file("rust/crates/flash-cjk-core/src/data/punct.rs", {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/lang/zhcn/data.json and",
	"// lua/flash-cjk/lang/ja/data.json -- DO NOT EDIT",
	"// Punctuation keys -> matched characters per language.",
	"",
	"pub static PUNCT_CN: &[(&str, &str)] = &[",
	table.concat(class_entries(zhcn.comma), ",\n"),
	"];",
	"",
	"pub static PUNCT_JP: &[(&str, &str)] = &[",
	table.concat(class_entries(ja_data.comma), ",\n"),
	"];",
})
print("done")
