package.path = "./lua/?.lua;./lua/?/init.lua;" .. package.path
-- Exports the Lua data tables to Rust static data: rust/data/*.rs and
-- rust/crates/flash-cjk-core/src/data/*.rs. Run: nvim -l scripts/export_rs.lua
-- Single source of truth: the Lua modules themselves (defaults only).

local function esc(s)
	return (s:gsub("[\\\"]", { ['\\'] = '\\\\', ['"'] = '\\"' }))
end

local function write_file(path, lines)
	local f = io.open(path, "w")
	f:write(table.concat(lines, "\n"))
	f:write("\n")
	f:close()
	print("wrote " .. path)
end

local rust_escape = function(c)
	if c == "\\" then
		return "\\\\"
	end
	return c
end

-- ---------------------------------------------------------------- zhcn data
local zhcn = require("flash-cjk.zhcnData")

local function table_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local out = {}
	for _, k in ipairs(keys) do
		local v = t[k]
		-- "[chars]" -> inner chars, escaped for Rust
		local inner = v:sub(2, -2)
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(inner))
	end
	return out
end

write_file("rust/data/flypy.rs", {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/zhcnData.lua -- DO NOT EDIT",
	"// Keys are 1-2 letter flypy codes; values are raw character-set strings.",
	"pub static CN_CHAR1: &[(&str, &str)] = &[",
	table.concat(table_entries(zhcn.char1patterns), ",\n"),
	"];",
	"",
	"pub static CN_CHAR2: &[(&str, &str)] = &[",
	table.concat(table_entries(zhcn.char2patterns), ",\n"),
	"];",
})

-- ---------------------------------------------------------------- ja data
local ja_data = require("flash-cjk.jaData")

local function p1_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local out = {}
	for _, k in ipairs(keys) do
		local v = t[k]
		local inner = v:sub(2, -2)
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(inner))
	end
	return out
end

-- p3 values may be "[class]" or "\(class\|literal\|literal\)":
-- split into the class part and the literal two-char alternatives.
local function p3_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local classes, literals = {}, {}
	for _, k in ipairs(keys) do
		local v = t[k]
		if v:sub(1, 2) == "\\(" then
			local body = v:sub(3, -3)
			local parts = vim.split(body, "\\|", { plain = true })
			for _, part in ipairs(parts) do
				if part:sub(1, 1) == "[" then
					classes[#classes + 1] = string.format('("%s", "%s")', esc(k), esc(part:sub(2, -2)))
				else
					literals[#literals + 1] = string.format('("%s", "%s")', esc(k), esc(part))
				end
			end
		else
			classes[#classes + 1] = string.format('("%s", "%s")', esc(k), esc(v:sub(2, -2)))
		end
	end
	return classes, literals
end

local p3_classes, p3_literals = p3_entries(ja_data.p3)

-- readings for labeler prediction (char -> comma-separated spellings)
local function readings_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local out = {}
	for _, k in ipairs(keys) do
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(table.concat(t[k], ",")))
	end
	return out
end

write_file("rust/data/jp_data.rs", {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/jaData.lua -- DO NOT EDIT",
	"// Romaji prefix -> character set (raw string), split by prefix length.",
	"pub static JP_P1: &[(&str, &str)] = &[",
	table.concat(p1_entries(ja_data.p1), ",\n"),
	"];",
	"",
	"pub static JP_P2: &[(&str, &str)] = &[",
	table.concat(p1_entries(ja_data.p2), ",\n"),
	"];",
	"",
	"// 3-letter prefixes: single-char classes and youon two-char literals.",
	"pub static JP_P3_CLASS: &[(&str, &str)] = &[",
	table.concat(p3_classes, ",\n"),
	"];",
	"",
	"pub static JP_P3_LIT: &[(&str, &str)] = &[",
	table.concat(p3_literals, ",\n"),
	"];",
	"",
	"// labeler support: char -> spellings (comma separated)",
	"pub static JP_READINGS: &[(&str, &str)] = &[",
	table.concat(readings_entries(ja_data.readings), ",\n"),
	"];",
})


-- ---------------------------------------------------------------- ko
local ko = require("flash-cjk.ko")
local jamo = ko.jamo

local function rust_str(v)
	return '"' .. esc(v) .. '"'
end

local ko_lines = {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/ko.lua -- DO NOT EDIT",
	"// Korean jamo tables, index-aligned by 0-based L/V/T (None marks the",
	"// tense shift jamo that plain lowercase typing cannot produce).",
	"",
	string.format("pub static KO_L_ROMA: [&[&str]; %d] = [", #jamo.l_roma),
}
for _, romas in ipairs(jamo.l_roma) do
	local parts = {}
	for _, r in ipairs(romas) do
		parts[#parts + 1] = rust_str(r)
	end
	ko_lines[#ko_lines + 1] = "    &[" .. table.concat(parts, ", ") .. "],"
end
ko_lines[#ko_lines + 1] = "];"

local function ko_flat(name, arr)
	ko_lines[#ko_lines + 1] = ""
	ko_lines[#ko_lines + 1] = string.format("pub static %s: [&str; %d] = [", name, #arr)
	for _, v in ipairs(arr) do
		ko_lines[#ko_lines + 1] = "    " .. rust_str(v) .. ","
	end
	ko_lines[#ko_lines + 1] = "];"
end
ko_flat("KO_V_ROMA", jamo.v_roma)
ko_flat("KO_T_ROMA", jamo.t_roma)

-- Key tables are 0-based (index-aligned with the roma arrays above);
-- the roma lengths are the authority, since # on holed arrays is a border.
local function ko_opts(name, keys, n)
	ko_lines[#ko_lines + 1] = ""
	ko_lines[#ko_lines + 1] = string.format("pub static %s: [Option<&str>; %d] = [", name, n)
	for i = 0, n - 1 do
		local v = keys[i]
		ko_lines[#ko_lines + 1] = "    " .. (v and ("Some(" .. rust_str(v) .. ")") or "None") .. ","
	end
	ko_lines[#ko_lines + 1] = "];"
end
ko_opts("KO_L_KEYS", jamo.l_keys, #jamo.l_roma)
ko_opts("KO_V_KEYS", jamo.v_keys, #jamo.v_roma)
ko_opts("KO_T_KEYS", jamo.t_keys, #jamo.t_roma)

write_file("rust/crates/flash-cjk-core/src/data/ko.rs", ko_lines)

-- ---------------------------------------------------------------- punct
-- Punctuation classes per language: vim collection "[chars]" -> the
-- inner chars (backslash escapes kept; the Rust side strips them).
local function punct_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local out = {}
	for _, k in ipairs(keys) do
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(t[k]:sub(2, -2)))
	end
	return out
end

write_file("rust/crates/flash-cjk-core/src/data/punct.rs", {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/zhcnData.lua and",
	"// lua/flash-cjk/ja.lua -- DO NOT EDIT",
	"// Punctuation keys -> matched characters per language.",
	"",
	"pub static PUNCT_CN: &[(&str, &str)] = &[",
	table.concat(punct_entries(zhcn.comma), ",\n"),
	"];",
	"",
	"pub static PUNCT_JP: &[(&str, &str)] = &[",
	table.concat(punct_entries(require("flash-cjk.ja").comma), ",\n"),
	"];",
})
print("done")
