#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///
"""Export the JSON dictionaries to Rust static data.

Writes rust/data/*.rs and rust/crates/flash-cjk-core/src/data/*.rs from
lua/flash-cjk/lang/*/data.json -- the single source of truth. Run:
uv run scripts/export_rs.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LANG = ROOT / "lua" / "flash-cjk" / "lang"


def load(code: str) -> dict:
    with open(LANG / code / "data.json", encoding="utf-8") as f:
        return json.load(f)


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_file(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


# "[chars]" values -> ("key", "inner chars") entries, escaped for Rust
def class_entries(table: dict[str, str]) -> list[str]:
    return [f'("{esc(k)}", "{esc(v[1:-1])}")' for k, v in sorted(table.items())]


# ---------------------------------------------------------------- zhcn

zhcn = load("zhcn")

write_file(
    ROOT / "rust/data/zhcn_data.rs",
    [
        "// AUTO-GENERATED by scripts/export_rs.py from lua/flash-cjk/lang/zhcn/data.json -- DO NOT EDIT",
        "// Keys are 1-2 letter xiaohe double-pinyin codes; values are raw character-set strings.",
        "pub static CN_CHAR1: &[(&str, &str)] = &[",
        ",\n".join(class_entries(zhcn["char1patterns"])),
        "];",
        "",
        "pub static CN_CHAR2: &[(&str, &str)] = &[",
        ",\n".join(class_entries(zhcn["char2patterns"])),
        "];",
    ],
)

# ---------------------------------------------------------------- ja

ja = load("ja")


# p3 values are "[class]" or "\(class\|literal\|literal\)": split into
# the class part and the literal two-char alternatives.
def p3_entries(table: dict[str, str]) -> tuple[list[str], list[str]]:
    classes: list[str] = []
    literals: list[str] = []
    for key, value in sorted(table.items()):
        if value[:2] == "\\(":
            for part in value[2:-2].split("\\|"):
                if part[:1] == "[":
                    classes.append(f'("{esc(key)}", "{esc(part[1:-1])}")')
                else:
                    literals.append(f'("{esc(key)}", "{esc(part)}")')
        else:
            classes.append(f'("{esc(key)}", "{esc(value[1:-1])}")')
    return classes, literals


p3_classes, p3_literals = p3_entries(ja["p3"])

# char -> comma-separated spellings, for labeler prediction
readings = [
    f'("{esc(char)}", "{esc(",".join(spellings))}")'
    for char, spellings in sorted(ja["readings"].items())
]

write_file(
    ROOT / "rust/data/ja_data.rs",
    [
        "// AUTO-GENERATED by scripts/export_rs.py from lua/flash-cjk/lang/ja/data.json -- DO NOT EDIT",
        "// Romaji prefix -> character set (raw string), split by prefix length.",
        "pub static JP_P1: &[(&str, &str)] = &[",
        ",\n".join(class_entries(ja["p1"])),
        "];",
        "",
        "pub static JP_P2: &[(&str, &str)] = &[",
        ",\n".join(class_entries(ja["p2"])),
        "];",
        "",
        "// 3-letter prefixes: single-char classes and youon two-char literals.",
        "pub static JP_P3_CLASS: &[(&str, &str)] = &[",
        ",\n".join(p3_classes),
        "];",
        "",
        "pub static JP_P3_LIT: &[(&str, &str)] = &[",
        ",\n".join(p3_literals),
        "];",
        "",
        "// labeler support: char -> spellings (comma separated)",
        "pub static JP_READINGS: &[(&str, &str)] = &[",
        ",\n".join(readings),
        "];",
    ],
)

# ---------------------------------------------------------------- ko

jamo = load("ko")

ko_lines = [
    "// AUTO-GENERATED by scripts/export_rs.py from lua/flash-cjk/lang/ko/data.json -- DO NOT EDIT",
    "// Korean jamo tables, index-aligned by 0-based L/V/T (None marks the",
    "// tense shift jamo that plain lowercase typing cannot produce).",
    "",
    f'pub static KO_L_ROMA: [&[&str]; {len(jamo["l_roma"])}] = [',
]
for romas in jamo["l_roma"]:
    spellings = ", ".join(f'"{esc(roma)}"' for roma in romas)
    ko_lines.append(f"    &[{spellings}],")
ko_lines.append("];")


def ko_flat(name: str, arr: list[str]) -> None:
    ko_lines.append("")
    ko_lines.append(f"pub static {name}: [&str; {len(arr)}] = [")
    for value in arr:
        ko_lines.append(f'    "{esc(value)}",')
    ko_lines.append("];")


ko_flat("KO_V_ROMA", jamo["v_roma"])
ko_flat("KO_T_ROMA", jamo["t_roma"])


# Key tables are index-aligned with the roma arrays; the roma lengths
# are the authority, since holed arrays decode with nil gaps.
def ko_opts(name: str, keys: list[str | None], n: int) -> None:
    ko_lines.append("")
    ko_lines.append(f"pub static {name}: [Option<&str>; {n}] = [")
    for i in range(n):
        value = keys[i]
        cell = f'Some("{esc(value)}")' if value is not None else "None"
        ko_lines.append(f"    {cell},")
    ko_lines.append("];")


ko_opts("KO_L_KEYS", jamo["l_keys"], len(jamo["l_roma"]))
ko_opts("KO_V_KEYS", jamo["v_keys"], len(jamo["v_roma"]))
ko_opts("KO_T_KEYS", jamo["t_keys"], len(jamo["t_roma"]))

write_file(ROOT / "rust/crates/flash-cjk-core/src/data/ko.rs", ko_lines)

# ---------------------------------------------------------------- punct
# Punctuation per language: vim collection "[chars]" -> inner chars
# (backslash escapes kept; the Rust side strips them).

write_file(
    ROOT / "rust/crates/flash-cjk-core/src/data/punct.rs",
    [
        "// AUTO-GENERATED by scripts/export_rs.py from lua/flash-cjk/lang/zhcn/data.json and",
        "// lua/flash-cjk/lang/ja/data.json -- DO NOT EDIT",
        "// Punctuation keys -> matched characters per language.",
        "",
        "pub static PUNCT_CN: &[(&str, &str)] = &[",
        ",\n".join(class_entries(zhcn["comma"])),
        "];",
        "",
        "pub static PUNCT_JP: &[(&str, &str)] = &[",
        ",\n".join(class_entries(ja["comma"])),
        "];",
    ],
)
print("done")
