package.path = "./lua/?.lua;./lua/?/init.lua;" .. package.path
-- Exports the Lua data tables to Rust static data (rust/data/*.rs).
-- Run: nvim -l scripts/export_rs.lua
-- Single source of truth: the Lua modules themselves (runtime state,
-- i.e. after any setup() customizations is NOT included -- defaults only).

local function esc(s)
	return (s:gsub("[\\\"]", { ['\\'] = '\\\\', ['"'] = '\\"' }))
end

local function write_file(path, lines)
	local f = io.open(path, "w")
	f:write(table.concat(lines, "\n"))
	f:write("\n")
	f:close()
	print("wrote " .. path)
end

local rust_escape = function(c)
	if c == "\\" then
		return "\\\\"
	end
	return c
end

-- ---------------------------------------------------------------- flypy
local flypy = require("flash-cjk.flypy")

local function table_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local out = {}
	for _, k in ipairs(keys) do
		local v = t[k]
		-- "[chars]" -> inner chars, escaped for Rust
		local inner = v:sub(2, -2)
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(inner))
	end
	return out
end

write_file("rust/data/flypy.rs", {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/flypy.lua -- DO NOT EDIT",
	"// Keys are 1-2 letter flypy codes; values are raw character-set strings.",
	"pub static CN_CHAR1: &[(&str, &str)] = &[",
	table.concat(table_entries(flypy.char1patterns), ",\n"),
	"];",
	"",
	"pub static CN_CHAR2: &[(&str, &str)] = &[",
	table.concat(table_entries(flypy.char2patterns), ",\n"),
	"];",
})

-- ---------------------------------------------------------------- jp
local jp = require("flash-cjk.jp_data")

local function p1_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local out = {}
	for _, k in ipairs(keys) do
		local v = t[k]
		local inner = v:sub(2, -2)
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(inner))
	end
	return out
end

-- p3 values may be "[class]" or "\(class\|literal\|literal\)":
-- split into the class part and the literal two-char alternatives.
local function p3_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local classes, literals = {}, {}
	for _, k in ipairs(keys) do
		local v = t[k]
		if v:sub(1, 2) == "\\(" then
			local body = v:sub(3, -3)
			local parts = vim.split(body, "\\|", { plain = true })
			for _, part in ipairs(parts) do
				if part:sub(1, 1) == "[" then
					classes[#classes + 1] = string.format('("%s", "%s")', esc(k), esc(part:sub(2, -2)))
				else
					literals[#literals + 1] = string.format('("%s", "%s")', esc(k), esc(part))
				end
			end
		else
			classes[#classes + 1] = string.format('("%s", "%s")', esc(k), esc(v:sub(2, -2)))
		end
	end
	return classes, literals
end

local p3_classes, p3_literals = p3_entries(jp.p3)

-- readings for labeler prediction (char -> comma-separated spellings)
local function readings_entries(t)
	local keys = {}
	for k in pairs(t) do
		keys[#keys + 1] = k
	end
	table.sort(keys)
	local out = {}
	for _, k in ipairs(keys) do
		out[#out + 1] = string.format('("%s", "%s")', esc(k), esc(table.concat(t[k], ",")))
	end
	return out
end

write_file("rust/data/jp_data.rs", {
	"// AUTO-GENERATED by scripts/export_rs.lua from lua/flash-cjk/jp_data.lua -- DO NOT EDIT",
	"// Romaji prefix -> character set (raw string), split by prefix length.",
	"pub static JP_P1: &[(&str, &str)] = &[",
	table.concat(p1_entries(jp.p1), ",\n"),
	"];",
	"",
	"pub static JP_P2: &[(&str, &str)] = &[",
	table.concat(p1_entries(jp.p2), ",\n"),
	"];",
	"",
	"// 3-letter prefixes: single-char classes and youon two-char literals.",
	"pub static JP_P3_CLASS: &[(&str, &str)] = &[",
	table.concat(p3_classes, ",\n"),
	"];",
	"",
	"pub static JP_P3_LIT: &[(&str, &str)] = &[",
	table.concat(p3_literals, ",\n"),
	"];",
	"",
	"// labeler support: char -> spellings (comma separated)",
	"pub static JP_READINGS: &[(&str, &str)] = &[",
	table.concat(readings_entries(jp.readings), ",\n"),
	"];",
})

print("done")
