// AUTO-GENERATED by scripts/export_rs.py from lua/flash-cjk/lang/zhcn/data.json and
// lua/flash-cjk/lang/ja/data.json -- DO NOT EDIT
// Punctuation keys -> matched characters per language.

pub static PUNCT_CN: &[(&str, &str)] = &[
("\"", "\"“”"),
("'", "'‘’"),
(",", ",，"),
(".", ".。"),
(":", ":："),
(";", ";；"),
("?", "?？"),
("[", "\\[【"),
("]", "\\]】")
];

pub static PUNCT_JP: &[(&str, &str)] = &[
("!", "!！"),
(",", ",、"),
("-", "ー‐-"),
(".", ".。"),
("?", "?？"),
("[", "\\[「『"),
("]", "\\]」』")
];
